name: Release

on:
  push:
    tags:
      - v**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - name: Copy release artifacts
        run: |
          mkdir release
          cp core/build/libs/*.jar release
          cp sdk/build/libs/*.jar release
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: _release
          path: release
          if-no-files-found: warn

  release-to-github:
    name: Push Latest Release
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set TAG_NAME in Environment
        # Subsequent jobs will have the computed tag name
        run: echo "TAG_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Download release artifacts
        uses: actions/download-artifact@v3
        with:
          name: _release
          path: dist
      - name: Create or Update Release
        env:
          # Required for the `hub` CLI
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./github-release.sh --asset-dir=dist --tag=${TAG_NAME}
